### ISSUE TITLE
VS2022 nmake build fails with broken udpUuid.h file

### ISSUE THREAD

**Issue by apnadkarni** [bohagan1/TclUDP#1]
Compilation error:
```
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\malloc.h(43): error C2054: expected '(' to follow 'unknown'
```

Cause is generated udpUuid.h file

```
#define VFS_VERSION_UUID \
git-232c3d8f088d31614001f2b816c3c8d3ab2e18f4
unknown
```

**Comment by apnadkarni** [comment]
The problem was both clauses of the `if` in makefile.vc that generates the git id were being executed. I could not figure out why. The DOS batch file syntax is one big mystery.

The problem only manifests if there is not already a manifest in the source root.

Pull request #2 has a proposed fix.

**Comment by bohagan1** [comment]
I incorporated the fix.

**Comment by apnadkarni** [comment]
Thanks.
